project:
  type: website
  output-dir: docs
  
website:
  title: "Rachel Zayar"
  navbar:
    left:
      - text: "Profile"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "Data Viz Gallery"
        menu:
          - text: "BBC 100 Women 2020"
            href: tidytuesday1.qmd
          - text: "SF Street Trees"
            href: tidytuesday2.qmd
      - text: "Love in Romeo & Juliet"
        href: project2.qmd
      - text: "Asia vs Other: 2020 Life Expectancy"
        href: project3.qmd
      - text: "DeepMindâ€“NHS Ethics"
        href: project4.qmd
      - text: "Sex Differences and Traffic Stops"
        href: project5.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

