project:
  type: website
  output-dir: docs
  
website:
  title: "Rachel Zayar"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Viz"
        menu:
          - text: "TidyTuesday 1"
            href: tidytuesday1.qmd
          - text: "TidyTuesday 2"
            href: tidytuesday2.qmd
      - text: "Project 2"
        href: project2.qmd
      - text: "Project 3"
        href: project3.qmd
      - text: "Project 4"
        href: project4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

